### ISSUE TITLE
Extra resources pulled from the page

### ISSUE THREAD

**Issue by xavivars** [apertium/apertium-regtest#10]
It seems these resources are not really needed (at least, they do not exist in the repo).

```
<link rel="stylesheet" type="text/css" href="local.css">
<script src="local.js"></script>
```

**Comment by TinoDidriksen** [comment]
Those are for local overrides. They're 404's in most repos, but some repos may want overrides and this is the only way to allow for those unless we want to generate the HTML.

**Comment by xavivars** [comment]
That makes sense! Thanks!
