### ISSUE TITLE
issue with apertium-regtest 0.9.1-3 on Ubuntu

### ISSUE THREAD

**Issue by jonorthwash** [apertium/apertium-regtest#40]
I'm using `apertium-regtest` 0.9.1-3 (on an Ubuntu cluster I don't administer) which was installed via `http://apertium.projectjj.com/apt/nightly noble/main amd64 Packages`.

This is what the main page looks like in the browser:

-----
![Screenshot from 2024-12-14 16-12-31](https://github.com/user-attachments/assets/19f63658-0975-4455-b24f-93460e213aa0)
-----

This is what the logs say:

```
$ apertium-regtest web -p 3001
Starting server
Open http://localhost:3001 in your browser
130.58.68.142 - - [14/Dec/2024 16:06:56] "GET / HTTP/1.1" 200 -
130.58.68.142 - - [14/Dec/2024 16:06:56] "GET /jquery.js HTTP/1.1" 200 -
130.58.68.142 - - [14/Dec/2024 16:06:56] "GET /bootstrap.css HTTP/1.1" 200 -
130.58.68.142 - - [14/Dec/2024 16:06:56] "GET /regtest.css HTTP/1.1" 200 -
130.58.68.142 - - [14/Dec/2024 16:06:56] code 404, message File not found
130.58.68.142 - - [14/Dec/2024 16:06:56] "GET /local.css HTTP/1.1" 404 -
130.58.68.142 - - [14/Dec/2024 16:06:56] "GET /bootstrap.js HTTP/1.1" 200 -
130.58.68.142 - - [14/Dec/2024 16:06:56] "GET /diff.js HTTP/1.1" 200 -
130.58.68.142 - - [14/Dec/2024 16:06:56] code 404, message File not found
130.58.68.142 - - [14/Dec/2024 16:06:56] "GET /local.js HTTP/1.1" 404 -
130.58.68.142 - - [14/Dec/2024 16:06:56] "GET /regtest.js HTTP/1.1" 200 -
130.58.68.142 - - [14/Dec/2024 16:06:56] code 404, message File not found
130.58.68.142 - - [14/Dec/2024 16:06:56] "GET /favicon.ico HTTP/1.1" 404 -
```

**Comment by mr-martian** [comment]
Same for me. The dev console says that `$ is not defined` and the full contents of `jquery.js` is `/* Not needed for cmdline use, but can be fetched from https://cdn.jsdelivr.net/npm/jquery@3.6/dist/jquery.min.js */`, so this looks to me like a packaging issue. @TinoDidriksen

**Comment by TinoDidriksen** [comment]
That was apertium-regtest from Ubuntu Noble, which correctly doesn't have the JS files bundled. apertium-regtest was missing from nightly noble - it's there now, so apt-get update + dist-upgrade will install it.

The Debian and Ubuntu packages do not bundle the JS parts - nightly does.
